version: '3.7'

services:
  meilisearch:
      image: getmeili/meilisearch:v1.7
      ports:
        - "7700:7700"
      environment:
        - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-BiJ_2XF_iQ00yrh2Jy_ThisIsADummyPassword-NFk}
      volumes:
        - meilisearch_data:/meili_data
      networks:
        backend:
          aliases:
            - meilisearch
      healthcheck:
        test: ["CMD", "curl", "-s", "-f", "http://localhost:7700/health"]
        interval: 10s
        timeout: 5s
        retries: 3
        start_period: 10s
  
  ui:
      image: qburstoss/finala:ui
      command: 
        - ui 
        - -c 
        - /etc/finala/config.yaml
      volumes:
          - ./configuration/ui.yaml:/etc/finala/config.yaml
      ports:
        - "8080:8080"
      networks:
        - backend
      depends_on: 
        - api
  api:
      image: qburstoss/finala:api
      entrypoint: ["/bin/finala"]
      command: 
        - api 
        - -c 
        - /etc/finala/config.yaml
        - --port=8081
      environment:
        - OVERRIDE_STORAGE_ENDPOINT=http://meilisearch:7700
        - OVERRIDE_STORAGE_PASSWORD=${MEILI_MASTER_KEY:-BiJ_2XF_iQ00yrh2Jy_ThisIsADummyPassword-NFk}
      volumes:
          - ./configuration/api.yaml:/etc/finala/config.yaml
      ports:
        - "8089:8081"
      restart: on-failure:3
      depends_on: 
        meilisearch:
          condition: service_healthy
      networks:
        backend:
          aliases:
            - api
  collector:
      image: qburstoss/finala:collector
      command: 
        - collector 
        - -c 
        - /etc/finala/config.yaml
      environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - OVERRIDE_API_ENDPOINT=http://api:8081
      volumes:
          - ./configuration/collector.yaml:/etc/finala/config.yaml
      networks:
        - backend
      depends_on: 
        - api
  # Uncomment the notifier after a first successful run of the Collector
  # notifier:
  #     image: qburstoss/finala:notifier
  #     command: 
  #       - notifier 
  #       - -c 
  #       - /etc/finala/config.yaml
  #     volumes:
  #         - ./configuration/notifier.yaml:/etc/finala/config.yaml
  #     networks:
  #       - backend
  #     depends_on: 
  #       - api
 
networks:
  backend:

volumes:
  meilisearch_data:
