name: Go
on: [push]
jobs:

  test:
    name: Code Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Set up Go from go.mod
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
      id: go
    - name: Run tests
      run: |
        make test    
        